---
title: "Heterogeneity Figures"
subtitle: "BQ Model"
output: html_document
---

```{r}
devtools::load_all("../ramp.micro")
```
```{r}
kFb = make_kF_exp(k=2, s=1, gamma=1)
kFq = make_kF_exp(k=2, s=1, gamma=1)
kFs = make_kF_exp(k=2, s=1, gamma=1)
```

```{r}
set.seed(2328)
bb = cbind(runif(256, -17, 17), runif(256, -17, 17))
xx = cbind(runif(13, -17, 17), runif(13, -17, 17))
qq = cbind(runif(289, -17, 17), runif(289, -17, 17))
ss = cbind(runif(225, -17, 17), runif(225, -17, 17))
disp_opts = list(kFb=kFb, kFq=kFq, kFs=kFs, stayB=0.1, stayQ=0.1, stayS=0.01)
```


```{r}
mod_f1 = setup_model(xx, bb, ss, Mname = "BQS", dispersal_opts=disp_opts)
mod_f1 <- basic_analysis(mod_f1)
```

```{r}
plotBQS = function(model, psz = 4){
  Beq = model$steady$M$B
  Qeq = model$steady$M$Q
  Seq = model$steady$M$S
  plot_points(model, wts_b=Beq, wts_q=Qeq, wts_s = Seq, cx_b=psz, cx_q=psz, cx_s = psz)
  outline_points_s(model$s, wts_s=Seq, cx_s=psz)
  outline_points_q(model$q, wts_q=Qeq, cx_q=psz)
  outline_points_b(model$b, wts_b=Beq, cx_b=psz)
}
```

```{r, fig.height=5, fig.width=5}
par(mar = c(1, 1, 3, 3))
plotBQS(mod_f1, 4)
mtext("a) 13 Habitats", 3, 1, cex=1.5)
```



```{r}
mod_f2 = setup_model(bb, xx, ss, Mname = "BQS", dispersal_opts=disp_opts)
mod_f2 <- basic_analysis(mod_f2)
```

```{r, fig.height=5, fig.width=5}
par(mar = c(1, 1, 3, 3))
plotBQS(mod_f2, 4)
mtext("b) 13 Habitats", 3, 1, cex=1.5)
```

```{r}
mod_f3 = setup_model(bb, qq, xx,  Mname = "BQS", dispersal_opts=disp_opts)
mod_f3 <- SIM(mod_f3, 1)
```


```{r}
mod_f3 <- basic_analysis(mod_f3)
```

```{r, fig.height=5, fig.width=5}
par(mar = c(1, 1, 3, 3))
plotBQS(mod_f3, 4)
mtext("c) 13 Sugar Sources", 3, 1, cex=1.5)
```

```{r, fig.height=5, fig.width=15}
par(mar = c(1, 1, 3, 3), mfrow = c(1,3))
plotBQS(mod_f1, 4)
mtext("a) Haunts are Rare", 3, 1, cex=1.5)
plotBQS(mod_f2, 4)
mtext("b) Habitats are Rare", 3, 1, cex=1.5)
plotBQS(mod_f3, 4)
mtext("c) Sugar is Rare", 3, 1, cex=1.5)
```

```{r}
png("rare.png", width=1440, height=480)
par(mar = c(1, 1, 3, 3), mfrow = c(1,3))
plotBQS(mod_f1, 4)
mtext("a) Haunts are Rare", 3, 1, cex=1.5)
plotBQS(mod_f2, 4)
mtext("b) Habitats are Rare", 3, 1, cex=1.5)
plotBQS(mod_f3, 4)
mtext("c) Sugar is Rare", 3, 1, cex=1.5)
dev.off(dev.cur())
```
